# -*- coding: utf-8 -*-
"""standard_metrics2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13I3htErGRHKLtvANI2xV3MNoi-qLLO9_

# **scispacy:**
"""

import spacy

# Load NER-specific model
nlp = spacy.load("en_ner_bc5cdr_md")

text = "Patient was prescribed aspirin for hypertension"
doc = nlp(text)

print("Medical Entities found:")
for ent in doc.ents:
    print(ent.text, ent.label_)



"""# **ClinicalBERT:**"""

# Install transformers and torch if not already installed
# !pip install transformers torch

from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline

# Load ClinicalBERT model (fine-tuned on clinical notes)
model_name = "emilyalsentzer/Bio_ClinicalBERT"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(model_name)

# Create NER pipeline
ner_pipeline = pipeline("ner", model=model, tokenizer=tokenizer, aggregation_strategy="simple")

# Medical text
text = "Patient shows symptoms of type 2 diabetes and hypertension"

# Run NER
entities = ner_pipeline(text)

# Print entities
print("ClinicalBERT Medical Entities found:")
for ent in entities:
    print(ent['word'], ent['entity_group'])





"""# **Regex Patterns for Extracting Numbers + Units**

# **1️.Basic Number Extraction**
"""

import re

text = "Patient was given 500 mg paracetamol twice daily for 5 days"
numbers = re.findall(r'\d+\.?\d*', text)
print(numbers)

"""## **2️.Number + Unit Extraction**"""

pattern = r'\b\d+\.?\d*\s?(mg|ml|g|kg|units|mcg|%)\b'
matches = re.findall(pattern, text, re.IGNORECASE)
print(matches)

"""# **3️.Full Dosage Extraction**"""

pattern = r'\b(\d+\.?\d*)\s?(mg|ml|units|mcg)\b'
matches = re.findall(pattern, text)
print(matches)

"""# **4️.Frequency Extraction**"""

freq_pattern = r'\b(once|twice|thrice|\d+\s?times)\s?(daily|a day)\b'
re.findall(freq_pattern, text, re.IGNORECASE)



text = "Insulin 2 units subcutaneously twice daily"

dose = re.findall(r'\b\d+\s?(units|mg|ml)\b', text)
freq = re.findall(r'\b(once|twice)\s?daily\b', text)

print(dose, freq)

!pip install word2number

"""# **Normalization Before Evaluation**

# **1.Convert Number Words to Digits**
"""

from word2number import w2n

text = "two milligrams"
number = w2n.word_to_num("two")
print(number)

"""# **2.Normalize Units Using Mapping**"""

unit_map = {
    "milligrams": "mg",
    "milligram": "mg",
    "micrograms": "mcg",
    "grams": "g"
}

text = "two milligrams"
for k, v in unit_map.items():
    text = text.replace(k, v)

print(text)

"""# **3.Combine Number + Unit**"""

normalized = f"{number} mg"
print(normalized)



import re

text = "The patient will return in 2 weeks"

pattern = r"\b\d+\s+(day|days|week|weeks|month|months)\b"
matches = re.findall(pattern, text)

print(matches)